# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clientaddinterview.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import hashlib
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_AddNewInterview(object):
    def setupUi(self, AddNewInterview):
        AddNewInterview.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        AddNewInterview.setObjectName("AddNewInterview")
        AddNewInterview.resize(690, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddNewInterview.sizePolicy().hasHeightForWidth())
        AddNewInterview.setSizePolicy(sizePolicy)
        AddNewInterview.setMinimumSize(QtCore.QSize(690, 180))
        AddNewInterview.setMaximumSize(QtCore.QSize(690, 180))
        AddNewInterview.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.label_3 = QtWidgets.QLabel(AddNewInterview)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 721, 41))
        self.label_3.setStyleSheet("background-color: rgb(37, 39, 44);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.addInterviewButton = QtWidgets.QPushButton(AddNewInterview)
        self.addInterviewButton.setGeometry(QtCore.QRect(275, 140, 144, 28))
        self.addInterviewButton.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.addInterviewButton.setFont(font)
        self.addInterviewButton.setStyleSheet("QPushButton{border-color: rgb(233, 151, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-color:rgb(233,151,0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"margin:  3px;}\n"
"QPushButton:Pressed{\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 151, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"margin:  3px;\n"
"}")
        self.addInterviewButton.setObjectName("addInterviewButton")
        self.intervieCode = QtWidgets.QTextEdit(AddNewInterview)
        self.intervieCode.setGeometry(QtCore.QRect(20, 90, 650, 30))
        self.intervieCode.setMinimumSize(QtCore.QSize(650, 0))
        self.intervieCode.setMaximumSize(QtCore.QSize(650, 30))
        self.intervieCode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intervieCode.setObjectName("intervieCode")
        self.label_2 = QtWidgets.QLabel(AddNewInterview)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 151, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_title_bar_top = QtWidgets.QLabel(AddNewInterview)
        self.label_title_bar_top.setGeometry(QtCore.QRect(10, 10, 201, 23))
        self.label_title_bar_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.addInterviewButton.clicked.connect(self.verifyCode)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.closeButton = QtWidgets.QPushButton(AddNewInterview)
        self.closeButton.setGeometry(QtCore.QRect(650, 0, 40, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(40, 0))
        self.closeButton.setMaximumSize(QtCore.QSize(40, 50))
        self.closeButton.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.closeButton.clicked.connect(self.closeForm)
        self.label_3.raise_()
        self.label_title_bar_top.raise_()
        self.closeButton.raise_()

        self.retranslateUi(AddNewInterview)
        QtCore.QMetaObject.connectSlotsByName(AddNewInterview)

    def closeForm(self):
        AddNewInterview.close()
    def verifyCode(self):
        code =self.intervieCode.toPlainText()
        if code == "":
            errorBox = QMessageBox()
            errorBox.setWindowTitle("Error")
            errorBox.setText("Please isnert an Interview code")
            errorBox.setIcon(QMessageBox.Critical)
            show = errorBox.exec_()
        else:
            code = code.encode("utf-8")
            code = hashlib.md5(code)
            code = code.hexdigest()
            print(code)
            #515f22ee7aaffc800ab9561910eb5bc2
    def retranslateUi(self, AddNewInterview):
        _translate = QtCore.QCoreApplication.translate
        AddNewInterview.setWindowTitle(_translate("AddNewInterview", "Form"))
        self.addInterviewButton.setText(_translate("AddNewInterview", "    Add Interview   "))
        self.label_2.setText(_translate("AddNewInterview", "Enter Interview Code"))
        self.label_title_bar_top.setText(_translate("AddNewInterview", "Add new Interview"))
        self.closeButton.setToolTip(_translate("AddNewInterview", "Close"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewInterview = QtWidgets.QWidget()
    ui = Ui_AddNewInterview()
    ui.setupUi(AddNewInterview)
    AddNewInterview.show()
    sys.exit(app.exec_())
